version: "3"

tasks:
  build:
    desc: Build Hextra documentation site under `exampleSite`
    cmds:
      - hugo --gc --minify --themesDir=../.. --source=exampleSite

  css:
    depends: [build]
    desc: Compile production CSS using PostCSS to `assets/css/compiled/main.css`
    cmds:
      - npm run build:css

  dev:
    desc: Start development server for Hextra theme
    cmds:
      - npm run dev:theme

  libs:
    desc: Download libs from CDN
    cmds:
      - curl -o assets/lib/flexsearch/flexsearch.bundle.min.js https://cdn.jsdelivr.net/npm/flexsearch@0.7.31/dist/flexsearch.bundle.min.js
      - curl -o assets/lib/mermaid/mermaid.min.js https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.min.js
